(defpackage #:agentcomms
  (:nicknames #:acp)
  (:use #:cl)
  (:import-from #:bordeaux-threads
                #:condition-notify
                #:condition-wait
                #:current-thread
                #:destroy-thread
                #:join-thread
                #:make-condition-variable
                #:make-lock
                #:make-recursive-lock
                #:make-thread
                #:thread-alive-p
                #:with-lock-held
                #:with-recursive-lock-held)
  (:import-from #:argo
                #:json-error
                #:json-false
                #:json-false-p
                #:json-limits
                #:json-object-p
                #:json-true-p
                #:make-json-limits)
  (:import-from #:serapeum
                #:->)
  (:export
   ;; Conditions
   #:acp-error
   #:acp-error-message
   #:acp-protocol-error
   #:acp-protocol-error-payload
   #:acp-message-too-large
   #:acp-message-too-large-limit
   #:acp-method-error
   #:acp-method-error-code
   #:acp-method-error-data
   #:acp-remote-error
   #:acp-remote-error-method
   #:acp-request-cancelled
   #:acp-timeout
   #:acp-timeout-seconds
   #:acp-connection-closed
   #:acp-capability-error
   #:acp-capability-error-capability
   #:acp-unsupported-version
   #:acp-unsupported-version-version
   #:acp-state-error
   ;; JSON values
   #:*json-maximum-depth*
   #:*json-maximum-nodes*
   #:*acp-maximum-message-characters*
   #:json-object
   #:json-get
   #:json-true-p
   #:json-object-p
   #:json-sequence->list
   #:json-encode
   #:json-decode
   ;; Buffered updates
   #:acp-update-buffer
   #:make-acp-update-buffer
   #:update-buffer-send
   #:update-buffer-flush
   ;; Channels
   #:acp-channel
   #:channel-maximum-message-characters
   #:channel-read-message
   #:channel-write-message
   #:channel-close
   #:channel-open-p
   #:acp-stream-channel
   #:make-acp-stream-channel
   #:acp-pipe-channel
   #:make-acp-channel-pair
   ;; Connections
   #:*acp-default-request-timeout*
   #:*acp-inbound-request*
   #:acp-peer
   #:peer-handle-request
   #:peer-handle-notification
   #:peer-connection-closed
   #:acp-connection
   #:make-acp-connection
   #:acp-connection-channel
   #:acp-connection-peer
   #:acp-connection-name
   #:acp-connection-request-timeout
   #:acp-connection-log-function
   #:acp-connection-close-reason
   #:connection-open-p
   #:connection-run
   #:connection-request
   #:connection-notify
   #:connection-cancel-request
   #:connection-close
   #:acp-inbound-request
   #:acp-inbound-request-identifier
   #:acp-inbound-request-method
   #:acp-inbound-request-cancelled-p
   #:acp-request-cancelled-p
   #:acp-check-cancelled
   ;; Schema
   #:*acp-protocol-version*
   #:*acp-supported-protocol-versions*
   #:*acp-schema-reference*
   #:acp-method-name
   #:acp-method-keyword
   #:acp-extension-method-p
   #:acp-error-code
   #:acp-invalid-params
   #:acp-authentication-required
   #:acp-resource-not-found
   #:stop-reason-string
   #:stop-reason-keyword
   #:tool-kind-string
   #:tool-kind-keyword
   #:tool-call-status-string
   #:tool-call-status-keyword
   #:plan-entry-priority-string
   #:plan-entry-priority-keyword
   #:plan-entry-status-string
   #:plan-entry-status-keyword
   #:permission-option-kind-string
   #:permission-option-kind-keyword
   #:permission-outcome-string
   #:permission-outcome-keyword
   #:content-role-string
   #:content-role-keyword
   #:content-type-string
   #:content-type-keyword
   #:tool-call-content-type-string
   #:tool-call-content-type-keyword
   #:session-update-kind-string
   #:session-update-kind-keyword
   #:config-option-category-string
   #:config-option-category-keyword
   #:mcp-transport-string
   #:mcp-transport-keyword
   #:auth-method-type-string
   #:auth-method-type-keyword
   #:elicitation-action-string
   #:elicitation-action-keyword
   #:acp-field
   #:acp-capability-enabled-p
   #:acp-implementation
   #:acp-boolean
   #:acp-agent-capabilities
   #:acp-client-capabilities
   #:acp-auth-method
   #:acp-terminal-auth-method
   #:acp-annotations
   #:acp-text-content
   #:acp-image-content
   #:acp-audio-content
   #:acp-resource-link
   #:acp-embedded-resource
   #:acp-content-type
   #:acp-content-text
   #:acp-validate-content-blocks
   #:acp-tool-call-content
   #:acp-diff-content
   #:acp-terminal-content
   #:acp-tool-call-location
   #:acp-tool-call
   #:acp-tool-call-update
   #:acp-plan-entry
   #:acp-available-command
   #:acp-session-mode
   #:acp-session-mode-state
   #:acp-config-select-option
   #:acp-config-select-group
   #:acp-config-option-select
   #:acp-config-option-boolean
   #:acp-permission-option
   #:acp-env-variable
   #:acp-http-header
   #:acp-mcp-server-stdio
   #:acp-mcp-server-http
   #:acp-mcp-server-sse
   #:acp-mcp-server-transport
   #:acp-validate-mcp-servers
   #:acp-name-value-pairs
   #:acp-update-user-message
   #:acp-update-agent-message
   #:acp-update-agent-thought
   #:acp-update-tool-call
   #:acp-update-tool-call-progress
   #:acp-update-plan
   #:acp-update-available-commands
   #:acp-update-current-mode
   #:acp-update-config-options
   #:acp-update-session-info
   #:acp-update-usage
   #:acp-update-kind
   #:acp-session-info
   ;; Agent role
   #:*acp-agent-implementation-name*
   #:*acp-agent-implementation-version*
   #:acp-prompt-cancelled
   #:acp-agent
   #:acp-agent-connection
   #:acp-agent-protocol-version
   #:acp-agent-client-capabilities
   #:acp-agent-client-info
   #:acp-agent-advertised-capabilities
   #:acp-agent-connect
   #:acp-agent-serve
   #:acp-agent-session
   #:acp-agent-session-ids
   #:acp-agent-session-identifier
   #:acp-agent-session-working-directory
   #:acp-agent-session-cancel-requested-p
   #:acp-agent-session-prompt-active-p
   #:agent-implementation
   #:agent-capabilities
   #:agent-auth-methods
   #:agent-authenticate
   #:agent-new-session
   #:agent-load-session
   #:agent-resume-session
   #:agent-close-session
   #:agent-prompt
   #:agent-cancel
   #:agent-set-mode
   #:agent-set-config-option
   #:agent-list-sessions
   #:agent-delete-session
   #:agent-logout
   #:agent-extension-request
   #:agent-extension-notification
   #:agent-session-cancelled-p
   #:agent-check-cancelled
   #:agent-client-capability-p
   #:agent-client-request
   #:agent-client-notify
   #:agent-send-update
   #:make-agent-update-buffer
   #:agent-request-permission
   #:agent-read-text-file
   #:agent-write-text-file
   #:agent-create-terminal
   #:agent-terminal-output
   #:agent-wait-for-terminal-exit
   #:agent-kill-terminal
   #:agent-release-terminal
   #:agent-create-elicitation
   #:agent-complete-elicitation
   ;; Client role
   #:*acp-client-implementation-name*
   #:*acp-client-implementation-version*
   #:acp-client
   #:acp-client-connection
   #:acp-client-protocol-version
   #:acp-client-agent-capabilities
   #:acp-client-agent-info
   #:acp-client-auth-methods
   #:acp-client-advertised-capabilities
   #:acp-client-connect
   #:client-implementation
   #:client-capabilities
   #:client-session-update
   #:client-request-permission
   #:client-read-text-file
   #:client-write-text-file
   #:client-create-terminal
   #:client-terminal-output
   #:client-wait-for-terminal-exit
   #:client-kill-terminal
   #:client-release-terminal
   #:client-create-elicitation
   #:client-elicitation-completed
   #:client-extension-request
   #:client-extension-notification
   #:client-agent-capability-p
   #:client-agent-request
   #:client-agent-notify
   #:client-initialize
   #:client-authenticate
   #:client-new-session
   #:client-load-session
   #:client-resume-session
   #:client-close-session
   #:client-prompt
   #:client-cancel
   #:client-set-mode
   #:client-set-config-option
   #:client-list-sessions
   #:client-delete-session
   #:client-logout
   ;; Standard I/O and subprocesses
   #:*acp-process-exit-seconds*
   #:*acp-process-kill-seconds*
   #:*acp-process-stderr-limit*
   #:acp-standard-io-channel
   #:acp-standard-error-log
   #:acp-serve-standard-io
   #:acp-process-channel
   #:acp-process-channel-process
   #:acp-process-channel-command
   #:acp-process-channel-stderr-text
   #:acp-process-channel-alive-p
   #:acp-process-channel-exit-code
   #:acp-launch-agent
   #:*acp-maximum-inbound-requests*
   #:acp-connection-maximum-inbound-requests
   #:acp-inbound-request-thread
   #:acp-absolute-path-p
   #:acp-validate-absolute-path))
